development:
  adapter: postgresql
  encoding: utf8
  database: ingredients
  pool: 5
  username: alexpurhalo
  password: 123123

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: ingredients_test
  pool: 5
  username: alexpurhalo
  password: 123123

production:
  url: <%= ENV['DATABASE_URL'] %>